### PR TITLE
solved bug 123

### PR DESCRIPTION
**Pull request by silviafrias**
Creating a pull request to review bug 123 branch. @elliottjhill, @mdinacci can you please review this?

### CODE REVIEW

**Comment by surrehman76** [comment]
Can one of the admins verify this patch?

**Comment by elliottjhill** [comment]
test it please

**Comment by elliottjhill** [comment]
test this please

**Comment by surrehman76** [comment]
test this please

**Comment by elliottjhill** [comment]
test this please

**Comment by elliottjhill** [comment]
test this please

**Comment by surrehman76** [comment]
test this please

**Comment by surrehman76** [comment]
ok to test

**Comment by surrehman76** [comment]
test this please

**Comment by surrehman76** [comment]
retest this please

**Comment by surrehman76** [comment]
retest this please

**Comment by surrehman76** [comment]
Build failed

**Pull request closed without merging**
