### PR TITLE
Added failing test

### PR DESCRIPTION
**Pull request by elliottjhill**
Creating a failing unit test partly to test Jenkins but also to conflict with Marcos changes.

### CODE REVIEW

**Comment by elliottjhill** [comment]
test this please

**Comment by elliottjhill** [comment]
can one of the admins verify this  patch

**Comment by surrehman76** [comment]
test this please

**Comment by elliottjhill** [comment]
Can one of the admins verify this patch?

**Comment by elliottjhill** [comment]
test this please

**Comment by surrehman76** [comment]
test this please

**Pull request merged**
