### PR TITLE
Added a unit test that fails

### PR DESCRIPTION
**Pull request by mdinacci**
I added a unit test that fails. I expect Jenkins to post a -1 in the comment, only once.

### CODE REVIEW

**Comment by elliottjhill** [comment]
Please test it

test it please

**Comment by surrehman76** [comment]
Can one of the admins verify this patch?

**Comment by elliottjhill** [comment]
please add to whitelist

**Comment by elliottjhill** [comment]
test this please

**Comment by surrehman76** [comment]
test it please

**Comment by elliottjhill** [comment]
test this please

**Comment by elliottjhill** [comment]
test this please

**Comment by elliottjhill** [comment]
test this please

**Comment by surrehman76** [comment]
test this please

**Comment by surrehman76** [comment]
test this please

**Comment by surrehman76** [comment]
retest this please

**Comment by elliottjhill** [comment]
Looks like pushing more commits isn't triggering rebuilds, is this because this is a merge commit? It should build automatically right?

**Comment by surrehman76** [comment]
ideally it should otherwise you have to say as comment to get it done?

**Comment by mdinacci** [comment]
this morning it was doing it, I hadn't had to say anything.

**Comment by surrehman76** [comment]
ok there was error as * was put which Jenkins did not like it, please try again

**Comment by surrehman76** [comment]
looks like you have to have all user names added which is not big deal so avoid using *, its good chatting client too :)

**Comment by elliottjhill** [comment]
Its doing it on other branches, maybe due to being a merge request. I'll look into it more. As discussed the * does work even if the plugin says it doesn't. 

retest this please

**Comment by elliottjhill** [comment]
test this please

**Comment by surrehman76** [comment]
ok so for merge request we can document that user has to explicitly say "test this please"

**Comment by blaisethom** [comment]
Hi @elliottjhill can you review?

**Comment by blaisethom** [comment]
Testing with @silviafrias . Do you get an email?

**Comment by silviafrias** [comment]
@blaisethom Yes, I do

**Pull request closed without merging**
