### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by elliottjhill**
Added unit tests to test Jenkins passing and automation. Along with .gitignore file to not add .pyc

### CODE REVIEW

**Comment by elliottjhill** [comment]
@VocalIQ/developers  Added a couple of unit tests to test out jenkins integration

**Comment by surrehman76** [comment]
test this please

**Comment by surrehman76** [comment]
Can one of the admins verify this patch?

**Comment by elliottjhill** [comment]
@surrehman76 I've added you to the developers group also can you now see the "Merge pull request" button?

**Comment by surrehman76** [comment]
ok @elliottjhill it did not send me email that you asked me to do merge pull request, I have option to do and am doing it now :)

**Pull request merged**
